blank_issues_enabled: false
contact_links:
  - name: SURTURBOT SUPPORT
    url: https://t.me/SURTUR_SUPPORT
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://ultroid.tech/
    about: Basic documentation for setting up.
